package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Banghe generated by hbm2java
 */
@Entity
@Table(name = "banghe", catalog = "quanlynhahang")
public class Banghe implements java.io.Serializable {

	private String maBan;
	private Nhanvien nhanvien;
	private Trangthai trangthai;
	private int soLuongKhach;
	private int soKhachToiDa;
	private Set<Chitietgoimenu> chitietgoimenus = new HashSet<Chitietgoimenu>(0);
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);

	public Banghe() {
	}

	public Banghe(String maBan, int soLuongKhach, int soKhachToiDa) {
		this.maBan = maBan;
		this.soLuongKhach = soLuongKhach;
		this.soKhachToiDa = soKhachToiDa;
	}

	public Banghe(String maBan, Nhanvien nhanvien, Trangthai trangthai, int soLuongKhach, int soKhachToiDa,
			Set<Chitietgoimenu> chitietgoimenus, Set<Hoadon> hoadons) {
		this.maBan = maBan;
		this.nhanvien = nhanvien;
		this.trangthai = trangthai;
		this.soLuongKhach = soLuongKhach;
		this.soKhachToiDa = soKhachToiDa;
		this.chitietgoimenus = chitietgoimenus;
		this.hoadons = hoadons;
	}

	@Id

	@Column(name = "MaBan", unique = true, nullable = false, length = 10)
	public String getMaBan() {
		return this.maBan;
	}

	public void setMaBan(String maBan) {
		this.maBan = maBan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNhanVienTruc")
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTrangThai")
	public Trangthai getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Trangthai trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "SoLuongKhach", nullable = false)
	public int getSoLuongKhach() {
		return this.soLuongKhach;
	}

	public void setSoLuongKhach(int soLuongKhach) {
		this.soLuongKhach = soLuongKhach;
	}

	@Column(name = "SoKhachToiDa", nullable = false)
	public int getSoKhachToiDa() {
		return this.soKhachToiDa;
	}

	public void setSoKhachToiDa(int soKhachToiDa) {
		this.soKhachToiDa = soKhachToiDa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banghe")
	public Set<Chitietgoimenu> getChitietgoimenus() {
		return this.chitietgoimenus;
	}

	public void setChitietgoimenus(Set<Chitietgoimenu> chitietgoimenus) {
		this.chitietgoimenus = chitietgoimenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banghe")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

}
