package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bangluong generated by hbm2java
 */
@Entity
@Table(name = "bangluong", catalog = "quanlynhahang")
public class Bangluong implements java.io.Serializable {

	private Integer maLuong;
	private Nhanvien nhanvien;
	private Date ngayGioNhan;
	private int tongCaLam;
	private Integer vangCoPhep;
	private Integer vangKhongPhep;
	private Integer thoiGianTre;
	private int tongLuong;

	public Bangluong() {
	}

	public Bangluong(Nhanvien nhanvien, Date ngayGioNhan, int tongCaLam, int tongLuong) {
		this.nhanvien = nhanvien;
		this.ngayGioNhan = ngayGioNhan;
		this.tongCaLam = tongCaLam;
		this.tongLuong = tongLuong;
	}

	public Bangluong(Nhanvien nhanvien, Date ngayGioNhan, int tongCaLam, Integer vangCoPhep, Integer vangKhongPhep,
			Integer thoiGianTre, int tongLuong) {
		this.nhanvien = nhanvien;
		this.ngayGioNhan = ngayGioNhan;
		this.tongCaLam = tongCaLam;
		this.vangCoPhep = vangCoPhep;
		this.vangKhongPhep = vangKhongPhep;
		this.thoiGianTre = thoiGianTre;
		this.tongLuong = tongLuong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaLuong", unique = true, nullable = false)
	public Integer getMaLuong() {
		return this.maLuong;
	}

	public void setMaLuong(Integer maLuong) {
		this.maLuong = maLuong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNhanVien", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayGioNhan", nullable = false, length = 19)
	public Date getNgayGioNhan() {
		return this.ngayGioNhan;
	}

	public void setNgayGioNhan(Date ngayGioNhan) {
		this.ngayGioNhan = ngayGioNhan;
	}

	@Column(name = "TongCaLam", nullable = false)
	public int getTongCaLam() {
		return this.tongCaLam;
	}

	public void setTongCaLam(int tongCaLam) {
		this.tongCaLam = tongCaLam;
	}

	@Column(name = "VangCoPhep")
	public Integer getVangCoPhep() {
		return this.vangCoPhep;
	}

	public void setVangCoPhep(Integer vangCoPhep) {
		this.vangCoPhep = vangCoPhep;
	}

	@Column(name = "VangKhongPhep")
	public Integer getVangKhongPhep() {
		return this.vangKhongPhep;
	}

	public void setVangKhongPhep(Integer vangKhongPhep) {
		this.vangKhongPhep = vangKhongPhep;
	}

	@Column(name = "ThoiGianTre")
	public Integer getThoiGianTre() {
		return this.thoiGianTre;
	}

	public void setThoiGianTre(Integer thoiGianTre) {
		this.thoiGianTre = thoiGianTre;
	}

	@Column(name = "TongLuong", nullable = false)
	public int getTongLuong() {
		return this.tongLuong;
	}

	public void setTongLuong(int tongLuong) {
		this.tongLuong = tongLuong;
	}

}
