package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calamviec generated by hbm2java
 */
@Entity
@Table(name = "calamviec", catalog = "quanlynhahang")
public class Calamviec implements java.io.Serializable {

	private String maCa;
	private Date gioBatDau;
	private Date gioKetThuc;
	private Set<Lichcalamviec> lichcalamviecs = new HashSet<Lichcalamviec>(0);

	public Calamviec() {
	}

	public Calamviec(String maCa, Date gioBatDau, Date gioKetThuc) {
		this.maCa = maCa;
		this.gioBatDau = gioBatDau;
		this.gioKetThuc = gioKetThuc;
	}

	public Calamviec(String maCa, Date gioBatDau, Date gioKetThuc, Set<Lichcalamviec> lichcalamviecs) {
		this.maCa = maCa;
		this.gioBatDau = gioBatDau;
		this.gioKetThuc = gioKetThuc;
		this.lichcalamviecs = lichcalamviecs;
	}

	@Id

	@Column(name = "MaCa", unique = true, nullable = false, length = 10)
	public String getMaCa() {
		return this.maCa;
	}

	public void setMaCa(String maCa) {
		this.maCa = maCa;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "GioBatDau", nullable = false, length = 8)
	public Date getGioBatDau() {
		return this.gioBatDau;
	}

	public void setGioBatDau(Date gioBatDau) {
		this.gioBatDau = gioBatDau;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "GioKetThuc", nullable = false, length = 8)
	public Date getGioKetThuc() {
		return this.gioKetThuc;
	}

	public void setGioKetThuc(Date gioKetThuc) {
		this.gioKetThuc = gioKetThuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calamviec")
	public Set<Lichcalamviec> getLichcalamviecs() {
		return this.lichcalamviecs;
	}

	public void setLichcalamviecs(Set<Lichcalamviec> lichcalamviecs) {
		this.lichcalamviecs = lichcalamviecs;
	}

}
