package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name = "hoadon", catalog = "quanlynhahang")
public class Hoadon implements java.io.Serializable {

	private Integer maHd;
	private Banghe banghe;
	private Nhanvien nhanvien;
	private String tenKhachHang;
	private String tenNhanVien;
	private int soLuongKhach;
	private Date ngayGio;
	private int tongTien;
	private boolean thanhToan;
	private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

	public Hoadon() {
	}

	public Hoadon(Banghe banghe, Nhanvien nhanvien, String tenKhachHang, int soLuongKhach, Date ngayGio, int tongTien,
			boolean thanhToan) {
		this.banghe = banghe;
		this.nhanvien = nhanvien;
		this.tenKhachHang = tenKhachHang;
		this.soLuongKhach = soLuongKhach;
		this.ngayGio = ngayGio;
		this.tongTien = tongTien;
		this.thanhToan = thanhToan;
	}

	public Hoadon(Banghe banghe, Nhanvien nhanvien, String tenKhachHang, String tenNhanVien, int soLuongKhach,
			Date ngayGio, int tongTien, boolean thanhToan, Set<Chitiethoadon> chitiethoadons) {
		this.banghe = banghe;
		this.nhanvien = nhanvien;
		this.tenKhachHang = tenKhachHang;
		this.tenNhanVien = tenNhanVien;
		this.soLuongKhach = soLuongKhach;
		this.ngayGio = ngayGio;
		this.tongTien = tongTien;
		this.thanhToan = thanhToan;
		this.chitiethoadons = chitiethoadons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaHD", unique = true, nullable = false)
	public Integer getMaHd() {
		return this.maHd;
	}

	public void setMaHd(Integer maHd) {
		this.maHd = maHd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaBan", nullable = false)
	public Banghe getBanghe() {
		return this.banghe;
	}

	public void setBanghe(Banghe banghe) {
		this.banghe = banghe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNhanVien", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Column(name = "TenKhachHang", nullable = false)
	public String getTenKhachHang() {
		return this.tenKhachHang;
	}

	public void setTenKhachHang(String tenKhachHang) {
		this.tenKhachHang = tenKhachHang;
	}

	@Column(name = "TenNhanVien")
	public String getTenNhanVien() {
		return this.tenNhanVien;
	}

	public void setTenNhanVien(String tenNhanVien) {
		this.tenNhanVien = tenNhanVien;
	}

	@Column(name = "SoLuongKhach", nullable = false)
	public int getSoLuongKhach() {
		return this.soLuongKhach;
	}

	public void setSoLuongKhach(int soLuongKhach) {
		this.soLuongKhach = soLuongKhach;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgayGio", nullable = false, length = 19)
	public Date getNgayGio() {
		return this.ngayGio;
	}

	public void setNgayGio(Date ngayGio) {
		this.ngayGio = ngayGio;
	}

	@Column(name = "TongTien", nullable = false)
	public int getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(int tongTien) {
		this.tongTien = tongTien;
	}

	@Column(name = "ThanhToan", nullable = false)
	public boolean isThanhToan() {
		return this.thanhToan;
	}

	public void setThanhToan(boolean thanhToan) {
		this.thanhToan = thanhToan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadon")
	public Set<Chitiethoadon> getChitiethoadons() {
		return this.chitiethoadons;
	}

	public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
		this.chitiethoadons = chitiethoadons;
	}

}
