package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lichcalamviec generated by hbm2java
 */
@Entity
@Table(name = "lichcalamviec", catalog = "quanlynhahang")
public class Lichcalamviec implements java.io.Serializable {

	private Integer maLich;
	private Calamviec calamviec;
	private Nhanvien nhanvien;
	private Trangthai trangthai;
	private Date thoiGian;
	private Integer thoiGianTre;

	public Lichcalamviec() {
	}

	public Lichcalamviec(Calamviec calamviec, Nhanvien nhanvien, Date thoiGian) {
		this.calamviec = calamviec;
		this.nhanvien = nhanvien;
		this.thoiGian = thoiGian;
	}

	public Lichcalamviec(Calamviec calamviec, Nhanvien nhanvien, Trangthai trangthai, Date thoiGian,
			Integer thoiGianTre) {
		this.calamviec = calamviec;
		this.nhanvien = nhanvien;
		this.trangthai = trangthai;
		this.thoiGian = thoiGian;
		this.thoiGianTre = thoiGianTre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MaLich", unique = true, nullable = false)
	public Integer getMaLich() {
		return this.maLich;
	}

	public void setMaLich(Integer maLich) {
		this.maLich = maLich;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaCa", nullable = false)
	public Calamviec getCalamviec() {
		return this.calamviec;
	}

	public void setCalamviec(Calamviec calamviec) {
		this.calamviec = calamviec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNhanVien", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTrangThai")
	public Trangthai getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Trangthai trangthai) {
		this.trangthai = trangthai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ThoiGian", nullable = false, length = 10)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "ThoiGianTre")
	public Integer getThoiGianTre() {
		return this.thoiGianTre;
	}

	public void setThoiGianTre(Integer thoiGianTre) {
		this.thoiGianTre = thoiGianTre;
	}

}
