package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phanquyen generated by hbm2java
 */
@Entity
@Table(name = "phanquyen", catalog = "quanlynhahang")
public class Phanquyen implements java.io.Serializable {

	private String maQuyen;
	private String tenGoi;
	private Set<Vitrinhanvien> vitrinhanviens = new HashSet<Vitrinhanvien>(0);

	public Phanquyen() {
	}

	public Phanquyen(String maQuyen, String tenGoi) {
		this.maQuyen = maQuyen;
		this.tenGoi = tenGoi;
	}

	public Phanquyen(String maQuyen, String tenGoi, Set<Vitrinhanvien> vitrinhanviens) {
		this.maQuyen = maQuyen;
		this.tenGoi = tenGoi;
		this.vitrinhanviens = vitrinhanviens;
	}

	@Id

	@Column(name = "MaQuyen", unique = true, nullable = false, length = 10)
	public String getMaQuyen() {
		return this.maQuyen;
	}

	public void setMaQuyen(String maQuyen) {
		this.maQuyen = maQuyen;
	}

	@Column(name = "TenGoi", nullable = false)
	public String getTenGoi() {
		return this.tenGoi;
	}

	public void setTenGoi(String tenGoi) {
		this.tenGoi = tenGoi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phanquyen")
	public Set<Vitrinhanvien> getVitrinhanviens() {
		return this.vitrinhanviens;
	}

	public void setVitrinhanviens(Set<Vitrinhanvien> vitrinhanviens) {
		this.vitrinhanviens = vitrinhanviens;
	}

}
