package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trangthai generated by hbm2java
 */
@Entity
@Table(name = "trangthai", catalog = "quanlynhahang")
public class Trangthai implements java.io.Serializable {

	private String maTt;
	private String ttbang;
	private String tenTt;
	private Set<Banghe> banghes = new HashSet<Banghe>(0);
	private Set<Lichcalamviec> lichcalamviecs = new HashSet<Lichcalamviec>(0);
	private Set<Chitietgoimenu> chitietgoimenus = new HashSet<Chitietgoimenu>(0);

	public Trangthai() {
	}

	public Trangthai(String maTt, String ttbang, String tenTt) {
		this.maTt = maTt;
		this.ttbang = ttbang;
		this.tenTt = tenTt;
	}

	public Trangthai(String maTt, String ttbang, String tenTt, Set<Banghe> banghes, Set<Lichcalamviec> lichcalamviecs,
			Set<Chitietgoimenu> chitietgoimenus) {
		this.maTt = maTt;
		this.ttbang = ttbang;
		this.tenTt = tenTt;
		this.banghes = banghes;
		this.lichcalamviecs = lichcalamviecs;
		this.chitietgoimenus = chitietgoimenus;
	}

	@Id

	@Column(name = "MaTT", unique = true, nullable = false, length = 10)
	public String getMaTt() {
		return this.maTt;
	}

	public void setMaTt(String maTt) {
		this.maTt = maTt;
	}

	@Column(name = "TTBang", nullable = false, length = 50)
	public String getTtbang() {
		return this.ttbang;
	}

	public void setTtbang(String ttbang) {
		this.ttbang = ttbang;
	}

	@Column(name = "TenTT", nullable = false, length = 50)
	public String getTenTt() {
		return this.tenTt;
	}

	public void setTenTt(String tenTt) {
		this.tenTt = tenTt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trangthai")
	public Set<Banghe> getBanghes() {
		return this.banghes;
	}

	public void setBanghes(Set<Banghe> banghes) {
		this.banghes = banghes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trangthai")
	public Set<Lichcalamviec> getLichcalamviecs() {
		return this.lichcalamviecs;
	}

	public void setLichcalamviecs(Set<Lichcalamviec> lichcalamviecs) {
		this.lichcalamviecs = lichcalamviecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trangthai")
	public Set<Chitietgoimenu> getChitietgoimenus() {
		return this.chitietgoimenus;
	}

	public void setChitietgoimenus(Set<Chitietgoimenu> chitietgoimenus) {
		this.chitietgoimenus = chitietgoimenus;
	}

}
