package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trinhdovitinh generated by hbm2java
 */
@Entity
@Table(name = "trinhdovitinh", catalog = "quanlynhahang")
public class Trinhdovitinh implements java.io.Serializable {

	private String maTdvt;
	private String tenGoi;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

	public Trinhdovitinh() {
	}

	public Trinhdovitinh(String maTdvt, String tenGoi) {
		this.maTdvt = maTdvt;
		this.tenGoi = tenGoi;
	}

	public Trinhdovitinh(String maTdvt, String tenGoi, Set<Nhanvien> nhanviens) {
		this.maTdvt = maTdvt;
		this.tenGoi = tenGoi;
		this.nhanviens = nhanviens;
	}

	@Id

	@Column(name = "MaTDVT", unique = true, nullable = false, length = 10)
	public String getMaTdvt() {
		return this.maTdvt;
	}

	public void setMaTdvt(String maTdvt) {
		this.maTdvt = maTdvt;
	}

	@Column(name = "TenGoi", nullable = false)
	public String getTenGoi() {
		return this.tenGoi;
	}

	public void setTenGoi(String tenGoi) {
		this.tenGoi = tenGoi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trinhdovitinh")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

}
