package entities;
// Generated Apr 5, 2016 10:07:51 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vitrinhanvien generated by hbm2java
 */
@Entity
@Table(name = "vitrinhanvien", catalog = "quanlynhahang")
public class Vitrinhanvien implements java.io.Serializable {

	private String maViTri;
	private Phanquyen phanquyen;
	private String tenGoi;
	private Set<Nhanvientheoca> nhanvientheocas = new HashSet<Nhanvientheoca>(0);
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

	public Vitrinhanvien() {
	}

	public Vitrinhanvien(String maViTri, Phanquyen phanquyen, String tenGoi) {
		this.maViTri = maViTri;
		this.phanquyen = phanquyen;
		this.tenGoi = tenGoi;
	}

	public Vitrinhanvien(String maViTri, Phanquyen phanquyen, String tenGoi, Set<Nhanvientheoca> nhanvientheocas,
			Set<Nhanvien> nhanviens) {
		this.maViTri = maViTri;
		this.phanquyen = phanquyen;
		this.tenGoi = tenGoi;
		this.nhanvientheocas = nhanvientheocas;
		this.nhanviens = nhanviens;
	}

	@Id

	@Column(name = "MaViTri", unique = true, nullable = false, length = 10)
	public String getMaViTri() {
		return this.maViTri;
	}

	public void setMaViTri(String maViTri) {
		this.maViTri = maViTri;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaQuyen", nullable = false)
	public Phanquyen getPhanquyen() {
		return this.phanquyen;
	}

	public void setPhanquyen(Phanquyen phanquyen) {
		this.phanquyen = phanquyen;
	}

	@Column(name = "TenGoi", nullable = false)
	public String getTenGoi() {
		return this.tenGoi;
	}

	public void setTenGoi(String tenGoi) {
		this.tenGoi = tenGoi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vitrinhanvien")
	public Set<Nhanvientheoca> getNhanvientheocas() {
		return this.nhanvientheocas;
	}

	public void setNhanvientheocas(Set<Nhanvientheoca> nhanvientheocas) {
		this.nhanvientheocas = nhanvientheocas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vitrinhanvien")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

}
